### ISSUE TITLE
node_vel_tgt is imprecise

### ISSUE THREAD

**Issue by xeger** [xeger/kos-ramp#4] opened 2015-06-20 04:09 UTC
We always end up with residual velocity. Why?

1) Rounding error ... seems unlikely; eliminate this hyp with some testing.

2) We plan the burn for time of closest approach, but it takes some time to perform. Maybe the target's velocity changes enough during that interval to create the error? Also seems unlikely as the error is rather large (~10 m/s at 200km orbit).

**Comment by fellipec** [comment] 2017-11-20 13:45
Looks the math is good.
The problem is, indeed as you predicted in item 2, that the burn doesn't happen instantaneously. 
The ship, coming from a higher orbit, is accelerating towards the lower (target) orbit, or if coming from a lower, is decelerating towards the higher orbit. The predictions the script compute are for a situation that happens in a very moment in time. Before and after that moment the ship is changing its speed.
Is possible to see that in this sequence of screenshots: https://imgur.com/a/x5uKV

1. First, just before the burn, the target speed is dropping.  It was 108.6m/s @ T-20 and dropped by itself to 107.8m/s @ T-13. The node was calculated as 105.7 m/s.

2. When the exact time of the node happens (I was late by 1s when made the screenshot) the target relative speed and the node delta-V are virtually the same. But we can't forget that besides the engine's acceleration, the orbit's acceleration is also changing the craft's speed.

3. The craft's speed keeps growing during the burn, and it accounts for the error. 

What I did to mitigate the problem was to move the burn ahead in time by the approximated half of burn time, that was already calculated in the [file](https://github.com/xeger/kos-ramp/blob/9af4e078c2aad86413e43c7ac1dbae511a92c0e9/node_vel_tgt.ks#L32). That way, together with `node.ks` starting to burn halfway through the burn time, the craft should finish the burn about the time it was calculated before. Is possible to [see it in action here.](https://youtu.be/RZ0YPIxI2Xw)

The *perfect* solution would be able to account for that. For that works, it's necessary to precisely know the time of the burn, and it's very hard to know it, because of changes in TWR during the burn, time that some engines take for "spool up" (and with some modded engines, even to spool down!), cosine errors of engines not parallel to the ship's axis and so on.

Another source of error is that probably the target ship doesn't have a perfectly circular orbit, so it's speed will also change over time, and also chances are that the previous Hohmann Transfer don't put our ship in a perfect orbit match with the target, and so the orbital speeds will be different and also introduce a small error.

During some tests that I made during this weekend with `rendezvous.ks` and `approach.ks` I noticed that even with perfect math, the execution of the burns is prone to introduce small errors. My suggestion is to deal with those errors in the script that uses `node_vel_tgt.ks` instead to try to perfect it.

**Comment by xeger** [comment] 2017-11-20 18:23
It sounds like a perfect analytical solution is beyond our abilities -- or maybe impossible, given floating-point error, VM delays, and so forth.

As you say, it's probably best to let the calling script fine tune velocity according to his needs (especially now that we can reuse the RCS cancel code).

**Comment by fellipec** [comment] 2017-11-20 21:15
Agree. Anyway, I got pretty consistent and good results in rendezvous and docking now. 
I'll close this issue because node_vel_tgt is as good as can get, and we should deal with errors in other ways.

**Closed as completed by fellipec** 2017-11-20 21:15 UTC
